### ISSUE TITLE
In View Invoice Tax Rate Decimal round off Issue 

### ISSUE THREAD

**Issue by ManikantaKakitapalli** [simpo-ai/Simpo-Web#50]
Login Website builder (dev-app.simpo.ai)
Generate website
click on publish
go to invoice module
create invoice
![Screenshot 2024-03-19 123234](https://github.com/simpo-ai/Simpo-Web/assets/162091639/aa1fc446-9d82-47a0-b1ba-dfed7becee2d)

**Comment by Princemonga01** [comment]
when we are creating invoice at bottom we have option for round off
