### ISSUE TITLE
Product module there is no delete option to delete product (need to add delete as per design)

### ISSUE THREAD

**Issue by ManikantaKakitapalli** [simpo-ai/Simpo-Web#78]
Login website builder (dev-app.simpo.ai)
go to product module 
see the listing 
no delete functionality(design and functionality)
![Screenshot 2024-03-22 171211](https://github.com/simpo-ai/Simpo-Web/assets/162091639/60c4380c-42a7-47f1-80c6-2b4037280bd8)

**Comment by Princemonga01** [comment]
Api required for same
